#!/usr/bin/bash
echo "[====installing deps====]"
sudo pacman --noconfirm -S paru
paru --noconfirm -S hyprland-git dunst bat cava fish kitty neofetch waybar-hyprland-git wofi rsync hyprpaper-git
echo "[====moving config====]"
rsync -r -a ./config ~/.config
sudo rsync ./util/cherry-blossom /usr/bin/
sudo chmod +x /usr/bin/cherry-blossom
sudo rsync ./util/cherry-blossom.desktop /usr/share/wayland-sessions/
echo "[====changing shell====]"
sudo chsh -s /usr/bin/fish
chsh -s /usr/bin/fish