#!/usr/bin/env bash

nohex=0

if [ $# -eq 0 ]; then
  echo "Usage: color <colorname> [-n]"
  echo "  -n: no hex"
  exit 1
fi

if [ $# -eq 2 ]; then
  if [ $2 == "-n" ]; then
    nohex=1
  fi
fi

if [ $nohex -eq 1 ]; then
  cat ~/.config/hypr/themes/colors | grep "^$1: " | grep -o "#[0-9a-fA-F]\{6\}" | sed 's/#//'
  exit 0
fi

cat ~/.config/hypr/themes/colors | grep "^$1: " | grep -o "#[0-9a-fA-F]\{6\}"
exit 0