#!/usr/bin/env sh

if ! [ -x "$(command -v asusctl)" ]; then
  notify-send "asusctl not found"
  exit 1
fi

current=$(asusctl -k | grep -Eo '[0-9]')

case $current in
    '0')
        ;;
    
    *)
        asusctl -p;;
esac