#!/usr/bin/env python
import subprocess
import os
import pywal

def apply(pre=None,wallpaper=None):
    if not pre:
        colors = pywal.colors.get(wallpaper,backend="colorz")
    else:
        colors = pre
    print(wallpaper)
    print("colors::::: ",colors)
    
    cmd = f"swww img '{wallpaper}' --transition-type simple --transition-step 15"
    subprocess.run(cmd,shell=True)
    
    with open(os.path.expanduser("~/.config/hypr/themes/colors"),"w") as f:
        for color,value in colors["colors"].items():
            f.write(f"{color[5:]}: {value}\n")
        for color,value in colors["special"].items():
            f.write(f"{color}: {value}\n")

    subprocess.run("touch ~/.config/hypr/themes/colors",shell=True)
    subprocess.run("pkill -USR2 fish",shell=True)

    # active borders
    gradient = ""
    for color,value in colors["colors"].items():
        gradient += f"rgba({value[1:]}ff) "
    gradient += " 45deg"
    cmd = f"hyprctl keyword general:col.active_border '{gradient}'"
    print(cmd)
    subprocess.run(cmd,shell=True)

    # inactive borders
    gradient = ""
    for color,value in colors["colors"].items():
        gradient += f"rgba({value[1:]}44) "
    gradient += " 0deg"
    cmd = f"hyprctl keyword general:col.inactive_border '{gradient}'"
    print(cmd)
    subprocess.run(cmd,shell=True)

    #keyboard
    cmd = f"asusctl led-mode static -c '{colors['colors']['color0'][1:]}'"
    print(cmd)
    subprocess.run(cmd,shell=True)

    #cava
    with open(os.path.expanduser("~/.config/cava/config"),"r") as f:
        conf = f.read()
    
    conf = conf.split("#--- cover2bg.py ---")[0]

    conf += "\n#--- cover2bg.py ---\n" + f"""
[color]
background = '{colors["special"]["background"]}'

gradient = 1

gradient_color_1 = '{colors["colors"]["color0"]}'
gradient_color_2 = '{colors["colors"]["color1"]}'
gradient_color_3 = '{colors["colors"]["color2"]}'
gradient_color_4 = '{colors["colors"]["color3"]}'
gradient_color_5 = '{colors["colors"]["color4"]}'
gradient_color_6 = '{colors["colors"]["color5"]}'
gradient_color_7 = '{colors["colors"]["color6"]}'
gradient_color_8 = '{colors["colors"]["color7"]}'
"""
    with open(os.path.expanduser("~/.config/cava/config"),"w") as f:
        f.write(conf)
    
    subprocess.run("pkill -USR2 cava",shell=True)

def main():
    apply(wallpaper="/tmp/bg.png")
    

if __name__ == "__main__":
    main()