#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# notification daemon
dunst &

foot -s -c $config/components/foot.ini &

swayidle -w timeout 300 '$HOME/.config/hypr/scripts/lock' timeout 600 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' before-sleep '$HOME/.config/hypr/scripts/lock' &

# # waybar
# $scripts/launch_waybar &
# $scripts/tools/dynamic &

# # wallpaper
# $scripts/wall $config/wallpapers/4.jpg &

# # effects
# $scripts/rgb &

# other
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
notify-send -a aurora "hello $(whoami)" &
