#!/usr/bin/env bash

nohex=0
colorfile=~/.config/hypr/themes/colors

if [ $# -eq 0 ]; then
  echo "Usage: color <colorname> [-n]"
  echo "  -n: no hex"
  exit 1
fi

if [ $# -eq 2 ]; then
  if [ $2 == "-n" ]; then
    nohex=1
  fi
  if [ $2 == "-u" ]; then
    colorfile=~/.config/hypr/themes/uicolors
  fi
  if [ $2 == "-un" ]; then
    nohex=1
  fi
fi

if [ $nohex -eq 1 ]; then
  cat $colorfile | grep "^$1: " | grep -o "#[0-9a-fA-F]\{6\}" | sed 's/#//'
  exit 0
fi

cat $colorfile | grep "^$1: " | grep -o "#[0-9a-fA-F]\{6\}"
exit 0